version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

# Options for custom base configuration file
#clash_rule_base = "https://raw.githubusercontent.com/zhongfly/clash-config/master/clash.yml"
#surge_rule_base = "base/surge.conf"
#surfboard_rule_base = "base/surfboard.conf"
#mellow_rule_base = "base/mellow.conf"
#quan_rule_base = "base/quan.conf"
#quanx_rule_base = "base/quanx.conf"

# Options for adding emojis
#add_emoji = true
#remove_old_emoji = true

# Options for filtering nodes
#include_remarks = []
#exclude_remarks = ["(æµé‡|æ—¶é—´|å®˜ç½‘|äº§å“|å…è´¹|è€—å°½|åˆ°æœŸ|è®¢é˜…|æ›´æ–°|ç¾¤ç»„)"]

# è®¾ç½®åˆ†ç»„æ ‡å¿—ä½
[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = [
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ”® è´Ÿè½½å‡è¡¡",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹",
    "[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢",
    "[]DIRECT"
]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ”® è´Ÿè½½å‡è¡¡"
type = "load-balance"
rule = ["(holymc)"]
interval = 300
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ’¬ OpenAi"
type = "select"
rule = ["[]ğŸ’¬ OpenAièŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§†é¢‘"
type = "select"
rule = ["[]ğŸ¥ å¥ˆé£èŠ‚ç‚¹","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]ğŸ¯ å…¨çƒç›´è¿","[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹","[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"]

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT","[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ† AdBlock"
type = "select"
rule = ["[]REJECT","[]DIRECT"]

[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]REJECT","[]DIRECT"]

[[custom_groups]]
name = "ğŸƒ åº”ç”¨å‡€åŒ–"
type = "select"
rule = ["[]REJECT","[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©","[]DIRECT"]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£èŠ‚ç‚¹"
type = "select"
rule = ["(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media|wiizero)"]

[[custom_groups]]
name = "ğŸ’¬ OpenAièŠ‚ç‚¹"
type = "select"
rule = ["(wiizero)"]




# ä¸ªäººè§„åˆ™
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/yxmyxmyyy/ACL4SSR/master/myconfig.list"

# ACL4SSR
[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"

[[rulesets]]
group = "ğŸƒ åº”ç”¨å‡€åŒ–"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"

[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
[[rulesets]]

group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ’¬ OpenAi"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"

[[rulesets]]
group = "ğŸ¶ ç½‘æ˜“éŸ³ä¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"

[[rulesets]]
group = "ğŸ“¹ æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
# è®¾ç½®è§„åˆ™æ ‡å¿—ä½
